name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Navigate to src folder and install dependencies
        run: cd test-workflow/src && npm install  

      - name: Run tests
        run: npm test  

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  
    steps:
      - name: Deploy Application
        run: echo "Deploying application..."
